### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [Piotrovskyi/kottans-js-2016#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by Piotrovskyi** [comment]
Done, так как несовсем понятно куда отправлять скрин, отправляю сюда :)
Скриншот
<https://github.com/Piotrovskyi/kottans-js-2016/blob/master/week01/task00/Screen%20Shot%202016-05-21%20at%2011.31.57%20PM.png?raw=true>

21 мая 2016 г., 14:27 пользователь Котэйка <notifications@github.com>
написал:

**Comment by Piotrovskyi** [comment]
https://github.com/Piotrovskyi/kottans-js-2016/blob/master/week01/task00/Screen%20Shot%202016-05-21%20at%2011.31.57%20PM.png?raw=true

**Comment by sudodoki** [comment]
LGTM
